<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-10T19:52:26 IST" name="Suite" finished-at="2023-02-10T19:54:15 IST" duration-ms="109881">
    <groups>
    </groups>
    <test started-at="2023-02-10T19:52:26 IST" name="Test-2" finished-at="2023-02-10T19:52:35 IST" duration-ms="9673">
      <class name="automation.TestDemo">
        <test-method signature="titleCheck()[pri:0, instance:automation.TestDemo@5215cd9a]" started-at="2023-02-10T19:52:26 IST" name="titleCheck" finished-at="2023-02-10T19:52:35 IST" duration-ms="9518" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at automation.TestDemo.titleCheck(TestDemo.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheck -->
      </class> <!-- automation.TestDemo -->
    </test> <!-- Test-2 -->
    <test started-at="2023-02-10T19:52:26 IST" name="Test-0" finished-at="2023-02-10T19:52:37 IST" duration-ms="11333">
      <class name="automation.TestDemo">
        <test-method signature="titleCheck()[pri:0, instance:automation.TestDemo@11ee02f8]" started-at="2023-02-10T19:52:26 IST" name="titleCheck" finished-at="2023-02-10T19:52:37 IST" duration-ms="11194" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at automation.TestDemo.titleCheck(TestDemo.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheck -->
      </class> <!-- automation.TestDemo -->
    </test> <!-- Test-0 -->
    <test started-at="2023-02-10T19:52:36 IST" name="TestGoogle-0" finished-at="2023-02-10T19:52:46 IST" duration-ms="10461">
      <class name="automation.TestDemo2">
        <test-method signature="titleCheckGoogle()[pri:0, instance:automation.TestDemo2@aa5455e]" started-at="2023-02-10T19:52:36 IST" name="titleCheckGoogle" finished-at="2023-02-10T19:52:46 IST" duration-ms="10403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheckGoogle -->
      </class> <!-- automation.TestDemo2 -->
    </test> <!-- TestGoogle-0 -->
    <test started-at="2023-02-10T19:52:26 IST" name="Test-1" finished-at="2023-02-10T19:52:48 IST" duration-ms="22273">
      <class name="automation.TestDemo">
        <test-method signature="titleCheck()[pri:0, instance:automation.TestDemo@5c371e13]" started-at="2023-02-10T19:52:26 IST" name="titleCheck" finished-at="2023-02-10T19:52:48 IST" duration-ms="22143" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at automation.TestDemo.titleCheck(TestDemo.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheck -->
      </class> <!-- automation.TestDemo -->
    </test> <!-- Test-1 -->
    <test started-at="2023-02-10T19:52:37 IST" name="TestGoogle-1" finished-at="2023-02-10T19:52:57 IST" duration-ms="20221">
      <class name="automation.TestDemo2">
        <test-method signature="titleCheckGoogle()[pri:0, instance:automation.TestDemo2@3d9fc57a]" started-at="2023-02-10T19:52:37 IST" name="titleCheckGoogle" finished-at="2023-02-10T19:52:57 IST" duration-ms="20166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheckGoogle -->
      </class> <!-- automation.TestDemo2 -->
    </test> <!-- TestGoogle-1 -->
    <test started-at="2023-02-10T19:52:46 IST" name="TestGoogle-2" finished-at="2023-02-10T19:54:15 IST" duration-ms="89463">
      <class name="automation.TestDemo2">
        <test-method signature="titleCheckGoogle()[pri:0, instance:automation.TestDemo2@5987e932]" started-at="2023-02-10T19:52:46 IST" name="titleCheckGoogle" finished-at="2023-02-10T19:54:15 IST" duration-ms="89406" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleCheckGoogle -->
      </class> <!-- automation.TestDemo2 -->
    </test> <!-- TestGoogle-2 -->
  </suite> <!-- Suite -->
</testng-results>
